PROJECT_NAME=webhook-manager
OUTPUT_DIRECTORY=./bin
BINARY=$OUTPUT_DIRECTORY/$PROJECT_NAME

TARGET_DIRECTORY=/usr/local/webhook-manager
TARGET=$TARGET_DIRECTORY/$PROJECT_NAME

WEBHOOK_SERVICE_FILE=webhook.service
SERVICE_FILE=webhook-manager.service
