PROJECT_NAME=webhook-api
OUTPUT_DIRECTORY=./bin
BINARY=$OUTPUT_DIRECTORY/$PROJECT_NAME

TARGET_DIRECTORY=/usr/local/webhook-api
TARGET=$DEPLOY_DIRECTORY/$PROJECT_NAME

WEBHOOK_SERVICE_FILE=webhook.service
SERVICE_FILE=webhook-api.service
